### ISSUE TITLE
add set voice and get voices

### ISSUE THREAD

**Issue by Eh2406** [Eh2406/rust-reader#2]
So that we can switch voices in settings.

**Comment by steinbro** [comment]
Hi! I looked into implementing this but quickly got turned off by the complexity of the COM API. I see that there's a newer Rust package https://github.com/vstojkovic/sapi-lite that provides a much nicer abstraction for interacting with voice selections, but it uses the wimdows-rs Win32 bindings instead of winapi. Is there any way to use that package without swapping out all the current bindings?

**Comment by Eh2406** [comment]
To your direct question it should be possible for a binary to use `wimdows-rs` and `Win32` bindings imported at the same time. (Or, porting over to the newer `wimdows-rs` would also be helpful.) I don't know whether `sapi-lite` provides a level of abstraction we would need for this project. But if it does, wonderful. If not we should be able to copy and modify what we need.

**Comment by steinbro** [comment]
Cool, I'm first attempting a port to `windows-rs` -- it's a little tedious, but it does give me the Rust practice I was looking for.
